#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-rollout
- name: "Install pip"
  become: true
  run_once: true
  package:
    name:
      - python3-pip

- name: "Install dependencies for the kubernetes.core.k8s module"
  become: true
  run_once: true
  pip:
    name:
      - kubernetes
      - pyyaml
      - jsonpatch

- name: "Loop over manifest templates"
  include_tasks: "tasks/handle_manifest_template.yml"
  loop: "{{ lookup('ansible.builtin.fileglob',
    'templates/*yml', wantlist=True) }}"
  loop_control:
    loop_var: manifest
