apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: dicty
  labels:
    app: dicty
spec:
  type: NodePort
  ports:
    - port: {{ k8s_rollout_dicty_svc_port }}
      nodePort: {{ k8s_rollout_dicty_svc_node_port }}
      protocol: TCP
  selector:
    app: dicty
