apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "db"
  labels:
    app: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30432
      protocol: TCP
  selector:
    app: db
